services:
  - type: web
    name: attendance-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EMAIL_USER
        value: vv708539@gmail.com
      - key: EMAIL_PASS
        value: osjx pfrw sjtc cglf
      # You can add the other receiver emails here as well if needed
      - key: RECEIVER_EMAIL
        value: krishnasurya2011@gmail.com
